(() => {
  'use strict';
  const c = window.SITE_CONTENT;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[ch]));
  const placeholder = text => `<p class="placeholder">${esc(text)}</p>`;
  const safeUrl = url => /^(https?:\/\/|mailto:|assets\/)/i.test(url || '') ? url : '';
  const link = (label, url, cls = 'button') => safeUrl(url) ? `<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} <span aria-hidden="true">↗</span><span class="sr-only"> (opens in a new tab)</span></a>` : '';
  const links = entries => { const html = entries.map(([label, url]) => link(label, url)).join(''); return html ? `<div class="actions">${html}</div>` : ''; };
  const media = (path, alt, label = 'Figure to come', cls = '') => path ? `<div class="media ${cls}"><div class="media-fallback"><span class="placeholder-mark" aria-hidden="true">＋</span><span>${esc(label)}</span></div><img src="${esc(path)}" alt="${esc(alt || label)}" loading="${cls === 'portrait' ? 'eager' : 'lazy'}"></div>` : '';
  const bullets = items => items?.length ? `<ul>${items.map(item => `<li>${esc(item)}</li>`).join('')}</ul>` : placeholder('Project notes to come.');
  const project = (p, i) => `<article class="project ${p.image ? '' : 'text-project'}">${media(p.image, p.imageAlt || p.title, 'Graphical abstract to come', 'scientific')}<div class="project-copy">${i === undefined ? '' : `<span class="eyebrow">Project ${String(i + 1).padStart(2, '0')}</span>`}<h4>${esc(p.title)}</h4>${p.dates ? `<p class="date">${esc(p.dates)}</p>` : ''}${p.description ? `<p>${esc(p.description)}</p>` : ''}${bullets(p.bullets)}${Array.isArray(p.ongoing) ? `<div class="ongoing"><h5>Ongoing Work</h5>${p.ongoing.length ? bullets(p.ongoing) : placeholder('Details to come.')}</div>` : ''}${links([['Paper', p.paper], ['Poster', p.poster], ['Conference', p.conference]])}</div></article>`;
  const section = (id, number, title, body) => `<section id="${id}" class="section"><div class="section-heading"><span class="section-number">${number}</span><h2>${title}</h2></div>${body}</section>`;
  const detail = value => value ? `<p>${esc(value)}</p>` : '';
  const role = r => `<article class="entry">${media(r.image, r.imageAlt || r.title, 'Photo to come')}<h4>${esc(r.title)}</h4>${detail(r.organization)}${r.dates ? `<p class="date">${esc(r.dates)}</p>` : ''}${r.description ? detail(r.description) : placeholder('Description to come.')}</article>`;
  document.querySelector('#main').innerHTML = `
    <section id="home" class="hero">
      <div class="hero-copy"><p class="eyebrow">Research & beyond</p><h1>${esc(c.profile.name)}</h1><p class="hero-title">${esc(c.profile.title)}</p>${c.profile.bio ? `<p class="bio">${esc(c.profile.bio)}</p>` : `<p class="bio placeholder">A short introduction to my research, interests,<br class="desktop-break"> and the questions that inspire me.<br><span class="placeholder-note">Bio to come.</span></p>`}<div class="socials">${Object.entries(c.profile.links).map(([name, url]) => safeUrl(url) ? link(name, url, 'social-link') : `<span class="social-pending" title="Link to be added">${esc(name)}<span class="sr-only"> — link to be added</span></span>`).join('')}</div><a class="explore" href="#projects">Explore my research <span aria-hidden="true">↓</span></a></div>${media(c.profile.image, c.profile.imageAlt, 'Portrait to come', 'portrait')}
    </section>
    ${section('projects', '01', 'Projects', `<div class="subsection"><h3>Ph.D. Projects</h3><div class="overview"><div><p class="eyebrow">Research overview</p>${c.overview.text ? detail(c.overview.text) : placeholder('A brief overview of my Ph.D. research will appear here.')} ${link('Visit my research group', c.overview.groupUrl, 'text-link')}${links([['View Overview Poster', c.overview.poster]])}</div>${media(c.overview.image, c.overview.imageAlt, 'Research overview image to come', 'scientific overview-image')}</div>${c.phd.map(project).join('')}</div><div class="subsection"><h3>Master’s Project</h3>${project(c.masters)}</div><div class="subsection"><h3>Side Projects</h3><div class="cards">${c.sideProjects.map(p => `<article class="entry side-card">${media(p.image, p.imageAlt, 'Project image to come')}<h4>${esc(p.title || 'Project title to come')}</h4>${p.description ? detail(p.description) : placeholder('A brief description to come.')}${links([['GitHub', p.github]])}</article>`).join('')}</div></div>`)}
    ${section('work', '02', 'Work Experience', c.work.map(w => `<article class="project">${media(w.image, w.imageAlt || w.organization, 'Work image to come', 'scientific')}<div><p class="eyebrow">${esc(w.organization)}</p><h3>${esc(w.title)}</h3>${w.dates ? `<p class="date">${esc(w.dates)}</p>` : ''}${w.bullets.length ? bullets(w.bullets) : placeholder('Experience notes to come.')}</div></article>`).join(''))}
    ${section('education', '03', 'Education', `<div class="subsection"><h3>Degrees</h3><div class="degree-list">${c.degrees.map(d => `<article class="degree"><div><h4>${esc(d.institution)}</h4><p>${esc(d.degree)}</p>${detail(d.description)}${d.researchTitle ? `<p class="research-title">Research: ${esc(d.researchTitle)}</p>` : ''}</div><p class="date ${d.dates ? '' : 'placeholder'}">${esc(d.dates || 'Dates to come')}</p></article>`).join('')}</div></div><div class="subsection"><h3>Certificates & Training</h3><div class="cards">${c.certificates.map(t => `<article class="entry"><h4>${esc(t.title || 'Certificate / training title to come')}</h4>${t.provider ? detail(t.provider) : placeholder('Provider to come.')}${t.date ? `<p class="date">${esc(t.date)}</p>` : ''}${detail(t.description)}${links([['View Certificate / Training', t.url]])}</article>`).join('')}</div></div>`)}
    ${section('conferences', '04', 'Conferences', Object.entries(c.conferences).map(([group, entries]) => `<div class="subsection"><h3>${esc(group)}</h3><div class="cards">${entries.map(e => `<article class="entry conference">${media(e.photo, e.imageAlt, 'Conference photo to come')}${media(e.thumbnail, e.imageAlt, 'Poster thumbnail to come', 'scientific')}<p class="date">${esc([e.year, e.location].filter(Boolean).join(' · ') || 'Year & location to come')}</p><h4>${esc(e.name || 'Conference name to come')}</h4>${e.title ? detail(e.title) : placeholder('Presentation title to come.')}${links([['View Poster', e.poster], ['Conference', e.url]])}</article>`).join('')}</div></div>`).join(''))}
    ${section('awards', '05', 'Awards & Honors', `<div class="awards">${[...c.awards].sort((a,b) => (Number(b.year) || 0) - (Number(a.year) || 0)).map(a => `<article class="award"><p class="date">${esc(a.year || 'Year to come')}</p><div><h3>${esc(a.title || 'Award title to come')}</h3>${a.organization ? detail(a.organization) : placeholder('Organization / event to come.')}${detail(a.description)}${media(a.image, a.imageAlt || a.title, 'Award photo to come')}</div></article>`).join('')}</div>`)}
    ${section('leadership', '06', 'Leadership & Outreach', Object.entries(c.leadership).map(([group, entries]) => `<div class="subsection"><h3>${esc(group)}</h3><div class="cards roles">${entries.map(role).join('')}</div></div>`).join(''))}
    ${section('beyond', '07', 'Beyond Research', `<div class="personal-grid">${c.personal.map(p => `<article class="personal-card">${media(p.image, p.imageAlt || p.title, 'Photo to come', 'personal-image')}<h3>${esc(p.title)}</h3>${detail(p.caption)}</article>`).join('')}</div>`)}
  `;
  document.querySelectorAll('.media img').forEach(img => {
    const loaded = () => { if (img.naturalWidth) img.parentElement.classList.add('loaded'); };
    img.addEventListener('load', loaded);
    img.addEventListener('error', () => { img.hidden = true; });
    if (img.complete) loaded();
  });
  const toggle = document.querySelector('.menu-toggle');
  const nav = document.querySelector('#navigation');
  const closeMenu = () => { toggle.setAttribute('aria-expanded', 'false'); nav.classList.remove('open'); };
  toggle.addEventListener('click', () => { const open = toggle.getAttribute('aria-expanded') !== 'true'; toggle.setAttribute('aria-expanded', String(open)); nav.classList.toggle('open', open); });
  nav.addEventListener('click', event => { if (event.target.closest('a')) closeMenu(); });
  document.addEventListener('keydown', event => { if (event.key === 'Escape' && toggle.getAttribute('aria-expanded') === 'true') { closeMenu(); toggle.focus(); } });
  if ('IntersectionObserver' in window) {
    const observer = new IntersectionObserver(entries => { entries.forEach(entry => { if (entry.isIntersecting) nav.querySelectorAll('a').forEach(a => { if (a.hash === `#${entry.target.id}`) a.setAttribute('aria-current', 'location'); else a.removeAttribute('aria-current'); }); }); }, { rootMargin: '-10% 0px -65% 0px', threshold: 0 });
    document.querySelectorAll('main > section').forEach(s => observer.observe(s));
  }
})();
